---
- name: themes | create
  copy:
    content: "{{ oh_my_zsh_themes[item[1]] }}"
    dest: "~{{ item[0].name }}/.oh-my-zsh/themes/{{ item[1] }}.zsh-theme"
    owner: "{{ item[0].name }}"
  with_nested:
    - "{{ oh_my_zsh_users }}"
    - "{{ oh_my_zsh_themes.keys() }}"
