---
- name: Oh-my-zsh | Users | shell
  user: name={{item.name}} shell=/bin/zsh
  with_items: oh_my_zsh_users

- name: Oh-my-zsh | Users | Setup
  command: "cp -R {{oh_my_zsh_tmp}} ~{{item.name}}"
  with_items: oh_my_zsh_users

- name: Oh-my-zsh | Users | Permissions
  file: >
    path="~{{item.name}}/.oh-my-zsh"
    owner={{item.name}}
    group={{item.name}}
    state=directory
    recurse=yes
  with_items: oh_my_zsh_users

- name: Oh-my-zsh | Users | Backup zshrc
  template: >
    src=zshrc.j2
    dest="~{{item.name}}/.zshrc"
    owner={{item.name}}
    group={{item.name}}
  with_items: oh_my_zsh_users
